### ISSUE TITLE
How to upgrade R1soft Server Backup Manager

### ISSUE THREAD

**Issue by bpersich** [IBM-Bluemix-Docs/software#2]
Issue posted by khayama commented on Feb 16--

Please update and document this topic in IBM Cloud Docs.
For the case of Vyatta, it's documented as follows.

Upgrade the OS
https://console.bluemix.net/docs/infrastructure/virtual-router-appliance/upgrade-os.html#upgrade-the-os

The users may have to contact IBM Cloud support to get the latest binary and upgrade.

**Comment by bpersich** [comment]
@khayama. I added a topic Ordering Software to explain how customers aquire software. This is the same procedure for R1Soft or any other software:
https://console.bluemix.net/docs/infrastructure/software/order-software.html#ordering-software

**Comment by khayama** [comment]
I’d like ask you to update how to upgrade R1soft version like Vyatta upgrade.
Do we have to issue a ticket and ask you to provide the newer software binary?
That kind of process is not clear.

**Comment by khayama** [comment]
Both cases are possible.
The thing I would like to point out is that you don't have any documentation about how to upgrade R1soft and apply patches on IBM Cloud.
We don't understand where to get the binary and which version should be allowed or validated on IBM Cloud and if I have to ask the support team per upgrade.
If it's the same as Vyatta, it'll be fine, but those point must be cleared on your documentation.
What do you think of it?

**Comment by khayama** [comment]
>By "get the binary", do you mean the installation files?
Yes, R1soft is licensed by IBM Cloud so we cannot get the install file directly.
Maybe this private link is the candidate but it's already old...
http://downloads.service.softlayer.com/r1soft/

>The way you install any software is to perform an OS reload and select the software you want to install. 
The new installation should be followed as you said.

>As far as patching software, I think IBM Cloud keeps up with patches.
No, the customer will have the responsibility to manage the software lifecycle after the provisioning.
However, IBM Cloud will have the responsibility to provide the validated and newer supported version.

**Comment by bpersich** [comment]
Ok. So I created a topic for installing software. That should cover new installations and installation of newest validated, supported versions.

If the customer need to maintain software patches, etc. Would they not get those from R1Soft?

**Comment by khayama** [comment]
Thanks
The third party software provided by IBM Cloud is licensed by IBM Cloud so usually each customer cannot get those update module like Vyatta.
Please confirm to the support team about how to get the newer modules.
For example, it may be through the support ticket.

**Comment by bpersich** [comment]
For R1Soft, the software is installed during provision or during an OS reload. IBM usually has the latest version. However, if there is a newer version, you can get it from R1Soft and install it. You'll have to check with R1Soft to make sure the license you purchased with IBM Cloud is valid for the version you are installing.

I have added topics to better detail the ordering process and what is required to upgrade

https://console.bluemix.net/docs/infrastructure/software/r1SoftUpgrade.html#upgrading-to-a-newer-version-of-r1soft

https://console.bluemix.net/docs/infrastructure/software/prov-R1Soft.html#ordering-r1soft
