### ISSUE TITLE
Document WSUS Servers

### ISSUE THREAD

**Issue by iSilverfyre** [IBM-Bluemix-Docs/software#4]
Followup for documentation regarding WSUS settings for the customer when using cloud init.  See #sl-virt-swimg-squads in slack.

**Comment by bpersich** [comment]
@iSilverfyre. This pages was updated for WSUS servers:
https://console.bluemix.net/docs/infrastructure/software/microsoft-windows-update-instructions.html#microsoft-windows-update-information

**Comment by gudrun-wolfgram** [comment]
New content for updating WSUS to local servers is live here:
Microsoft Windows Update Information
https://console.bluemix.net/docs/infrastructure/software/microsoft-windows-update-instructions.html

Updating an instance to use a local WSUS server
https://console.bluemix.net/docs/infrastructure/software/local-wsus.html

@bpersich You can close this out now. Looks like I don't have authority to do that.
